version: "3.9"
services:

  eurekaServer:
    build: ..\spring-boot-Microservices-Demo\Eureka-Discovery-Server\ .
    image: eurekaserver:1.0
    ports: 
      - 8761:8761
    networks: 
     - spring-network

  zuulServer:
   build: ..\spring-boot-Microservices-Demo\Zuul\ .
   image: zuulserver:1.0
   ports: 
     - 8080:8080
   environment: 
     # Important for clients to register with eureka
     - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
   depends_on:
     - eurekaServer
   networks: 
     - spring-network
   
  movie-catalog-service:
   build: ..\spring-boot-Microservices-Demo\Movie-catalog-Service\ .
   image: movie-catalog-service:1.0
   ports: 
     - 8081:8081
   environment: 
     - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
   depends_on:
     - eurekaServer
     - zuulServer
   networks: 
     - spring-network

  movie-info-service:
   build: ..\spring-boot-Microservices-Demo\Movie-Info-Service\ .
   image: movie-info-service:1.0
   ports: 
     - 8082:8082
   environment: 
     - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
   depends_on:
     - eurekaServer
     - zuulServer
   networks: 
     - spring-network

  rating-data-service:
   build: ..\spring-boot-Microservices-Demo\Ratings-Data-Service\ .
   image: rating-data-service:1.0
   ports: 
     - 8083:8083
   environment: 
     - eureka.client.serviceUrl.defaultZone=http://eurekaServer:8761/eureka/
   networks: 
     - spring-network
   depends_on:
     - eurekaServer
     - zuulServer

networks: 
  spring-network:
    driver: bridge
    
 