# our base build image
FROM maven:3.6.3-adoptopenjdk-14 AS maven

# copy the project files
COPY ./pom.xml ./pom.xml

# build all dependencies
RUN mvn dependency:go-offline -B

# copy your other files
COPY ./src ./src

# build for release
RUN mvn clean package


FROM openjdk:14-jdk-alpine

LABEL maintainer="Ash"

COPY --from=maven /target/Eureka-Discovery-Server-0.0.1-SNAPSHOT.jar /Eureka-Discovery-Server-0.0.1-SNAPSHOT.jar

EXPOSE 8761:8761

CMD ["java", "-jar", "/Eureka-Discovery-Server-0.0.1-SNAPSHOT.jar"]